# Generated by Django 5.1.3 on 2026-06-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='numero_de_membros',
            field=models.IntegerField(default=1),
        ),
    ]
