# Generated by Django 5.1.3 on 2026-06-16 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_hard_skills',
                'unique_together': {('user', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='hard_skills',
            field=models.ManyToManyField(blank=True, related_name='hard_skill_users', through='api.UserHardSkill', to='api.tag'),
        ),
        migrations.CreateModel(
            name='UserInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_interesses',
                'unique_together': {('user', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='interesses',
            field=models.ManyToManyField(blank=True, related_name='interesse_users', through='api.UserInteresse', to='api.tag'),
        ),
    ]
