# Generated by Django 5.1.3 on 2026-06-17 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userhardskill_user_hard_skills_userinteresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hard_skills',
        ),
        migrations.DeleteModel(
            name='UserHardSkill',
        ),
    ]
