# Generated by Django 5.1.3 on 2026-06-17 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_hard_skills_delete_userhardskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interesses',
        ),
        migrations.DeleteModel(
            name='UserInteresse',
        ),
    ]
