# Generated by Django 5.1.3 on 2026-06-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_interesses_delete_userinteresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='project',
            name='numero_membros',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
